version: "3.9"

services:
  reverse-proxy:
    image: nginx:1.21.6-alpine
    container_name: reverse-proxy
    depends_on:
      - web
      - dashboard
    ports:
      - 80:80
      # - 443:443
    environment:
      - TZ=Europe/Vilnius
    volumes:
      - ./proxy/logs/:/var/log/nginx/:rw
      - ./proxy/conf.d/:/etc/nginx/conf.d/:ro
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      # - /etc/letsencrypt/:/etc/nginx/ssl/:ro
      # - /etc/ssl/dhparamcerts.pem:/etc/ssl/dhparamcerts.pem:ro
      # - /var/www/html/:/var/www/html/:ro
    networks:
      - proxy

networks:
  proxy:
    name: proxy